### ISSUE TITLE
Milestone 2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI-522_Titanic-Survival-Prediction#65]
- [x] Provide an intro to your data analysis and a context to your question (e.g., the relevance of your question). 
- [x] State the question in your report
- [x] Create a unit test for the function `save_and_show_decision_tree()` in the script `fit-decision-tree.py`
- [x] Regarding your Makefile, I don't see results/plot_decision-tree.png` nor `results/eda_barplot-survival.png` as an input for your rendered report. 
- [x] mention the variables types (e.g., categorical, numeric, etc)

**Viz**
- [x] Label table 1
- [x] Plot the decision tree and interpret them. Make sure the plot is readable. Text should not be too small and not cramped. You may want to put some text in a table instead of in the decision tree plot. 

**Reasoning**
- [x] Okay, so sex and passenger class are the most important predictors. What does that mean? Example, if you are a male are you more likely to die?

**Comment by aimirza** [comment]
I provided a lot of comments. That is because I could not find the Milestone1 issues I have recorded last week. I might have forgotten to click on the "Comment" button.

**Comment by aldenchen** [comment]
We've addressed the issues you've listed. The most significant changes are in the report.
